# Generated by Django 6.0.3 on 2026-04-19 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactenquiry',
            name='subject',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
