# Generated by Django 6.0.3 on 2026-05-09 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_portfolioitem_service_siteimage_sitesetting_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='team/'),
        ),
    ]
