# Generated by Django 6.0.3 on 2026-05-09 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_teammember_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolioitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='portfolio/'),
        ),
        migrations.AddField(
            model_name='portfolioitem',
            name='video_id',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
