# Generated by Django 6.0.3 on 2026-05-12 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_client'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpcomingEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='upcoming_events/')),
                ('image_url', models.URLField(blank=True, help_text='External image URL (Unsplash etc)')),
                ('price_display', models.CharField(help_text='e.g. ₹5,00,000+', max_length=50)),
                ('event_date', models.DateField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order', 'event_date'],
            },
        ),
    ]
